//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cliente.WCF {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.IServiceRest")]
    public interface IServiceRest {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRest/RetornaCidades", ReplyAction="http://tempuri.org/IServiceRest/RetornaCidadesResponse")]
        System.Collections.Generic.Dictionary<int, string> RetornaCidades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRest/RetornaCidades", ReplyAction="http://tempuri.org/IServiceRest/RetornaCidadesResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> RetornaCidadesAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRest/Login", ReplyAction="http://tempuri.org/IServiceRest/LoginResponse")]
        string Login(string email, string password);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceRest/Login", ReplyAction="http://tempuri.org/IServiceRest/LoginResponse")]
        System.Threading.Tasks.Task<string> LoginAsync(string email, string password);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceRestChannel : Cliente.WCF.IServiceRest, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceRestClient : System.ServiceModel.ClientBase<Cliente.WCF.IServiceRest>, Cliente.WCF.IServiceRest {
        
        public ServiceRestClient() {
        }
        
        public ServiceRestClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceRestClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRestClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceRestClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<int, string> RetornaCidades() {
            return base.Channel.RetornaCidades();
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<int, string>> RetornaCidadesAsync() {
            return base.Channel.RetornaCidadesAsync();
        }
        
        public string Login(string email, string password) {
            return base.Channel.Login(email, password);
        }
        
        public System.Threading.Tasks.Task<string> LoginAsync(string email, string password) {
            return base.Channel.LoginAsync(email, password);
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WCF.IServiceSoap")]
    public interface IServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSoap/Registo", ReplyAction="http://tempuri.org/IServiceSoap/RegistoResponse")]
        bool Registo(string email);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IServiceSoap/Registo", ReplyAction="http://tempuri.org/IServiceSoap/RegistoResponse")]
        System.Threading.Tasks.Task<bool> RegistoAsync(string email);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IServiceSoapChannel : Cliente.WCF.IServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServiceSoapClient : System.ServiceModel.ClientBase<Cliente.WCF.IServiceSoap>, Cliente.WCF.IServiceSoap {
        
        public ServiceSoapClient() {
        }
        
        public ServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public bool Registo(string email) {
            return base.Channel.Registo(email);
        }
        
        public System.Threading.Tasks.Task<bool> RegistoAsync(string email) {
            return base.Channel.RegistoAsync(email);
        }
    }
}
